version: '3.8'
services:
  web:
    container_name: turbotraffic-web
    restart: always
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_GATEWAY_URL=http://localhost:3001/api/v1/
    build: .