version: '3.8'
services:
  web:
    image: node:16-alpine
    container_name: turbotraffic-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_GATEWAY_URL=http://localhost:3001/api/v1/
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start