version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=turbotraffic
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    container_name: turbotraffic-api
    restart: always
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE=turbotraffic
      - DATABASE_HOST=db
      - DATABASE_DELETE_SNYC=false
    build: .
    ports:
      - '3001:3001'
volumes:
  pgstore:
