version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=turbotraffic
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    container_name: turbotraffic-API
    depends_on:
    - db
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/usr/src/app