version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=turbotraffic
    ports:
      - '5432:5432'
  api:
    container_name: turbotraffic-API
    depends_on:
    - db
    restart: always
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE=turbotraffic
      - DATABASE_HOST=db
      - DATABASE_DELETE_SNYC=false
    build: .
    ports:
      - "3001:3001"
    links:
      - db
    volumes:
      - .:/usr/src/app